### PR TITLE
[stable/cstor]: update cstor charts to 2.5.0

### PR DESCRIPTION
**Pull request by akhilerm**
- update chart version and dependency version
- update README
- update values.yaml
- update snapshot CRDs
- update cspc operator and cvc operator deployment
- update csi-controller
- update csi-controller-rbac

Documentation update in #230 

Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>

### CODE REVIEW

**Review by prateekpandey14 — COMMENTED** [review]
@akhilerm can we add the volumesnapshotclass CR template as well

**Comment by akhilerm** [comment]
> @akhilerm can we add the volumesnapshotclass CR template as well

Done. @prateekpandey14

**Review by shubham14bajpai — APPROVED** [review]
lgtm

**Review by prateekpandey14 — APPROVED** [review]
Lgtm

**Pull request merged**
