### PR TITLE
Remove unused struct CmdSnaphotOptions

### PR DESCRIPTION
**Pull request by soniasingla**
Signed-off-by: Sonia Singla <soniasingla.1812@gmail.com>

### CODE REVIEW

**Comment by sonasingh46** [comment]
@soniasingla -- Can you please resolve the conflict.

**Comment by soniasingla** [comment]
@sonasingh46 thanks updated 🤗

**Comment by sonasingh46** [comment]
@prateekpandey14 @mittachaitu @soniasingla -- 
I think we are not even using this struct `CmdSnaphotOptions` anywhere. 
Please confirm.

**Comment by mittachaitu** [comment]
> @prateekpandey14 @mittachaitu @soniasingla --
> I think we are not even using this struct `CmdSnaphotOptions` anywhere.
> Please confirm.

Yes @sonasingh46 we can remove it

**Review by sonasingh46 — APPROVED** [review]

**Review by mittachaitu — APPROVED** [review]
lgtm

**Comment by soniasingla** [comment]
@kmova @mittachaitu updated the PR sorry for delay

**Review by mittachaitu — APPROVED** [review]
LGTM

**Pull request merged**
