### PR TITLE
Added Gitpod config

### PR DESCRIPTION
**Pull request by JanKoehnlein**
Hi OpenEBS team! 👋

here is a PR that fully-automates the dev setup of cstor-operators with Gitpod, providing anyone with a pre-built, browser-based development environment in one click:

[Open in Gitpod](https://gitpod.io/#https://github.com/$project/$repo)

Screen Shot 2021-05-04 at 16 59 00

## What it does

* Comes with all dependencies pre-installed (including Go, Docker, etc.)
* Runs `make all` ahead-of-time so you don't need to wait
* Gives anyone immediate access to the pre-compiled cstor-operators CLI, and allows to easily edit & rebuild the code

I hope this can make life easier for contributors, and for maintainers who need to review many PRs (hint: you can already open this PR in Gitpod to easily review & test it without messing up your local checkout).

Please let me know if I should open issues for these & how they can be fixed (e.g. in the generator).

And I'm looking forward to your feedback on this PR! 🚀

### CODE REVIEW

**Comment by JanKoehnlein** [comment]
sign-off added

**Comment by sonasingh46** [comment]
@JanKoehnlein -- Thanks for the PR. 
One naive question: ( Just Curious )
1. Is the go extension enabled by default in the editor? I tried and seems it is not.

**Comment by JanKoehnlein** [comment]
Good catch, I forgot to push the extension section. Now every user gets the Go and Docker extensions pre-installed.

Gitpod (SaaS) is [free for everybody for 50h per month/per user on public repos](https://www.gitpod.io/pricing), which is usually enough to make relevant contributions. For professional open-source developers, we offer a [free plan with unlimited hours on public repos](https://www.gitpod.io/docs/professional-open-source). Let us know if you're interested.

**Comment by kmova** [comment]
thanks @JanKoehnlein - for the info. I went ahead and submitted a request for Open Source plan for https://github.com/openebs org.

**Review by sonasingh46 — APPROVED** [review]
lgtm

**Review by prateekpandey14 — APPROVED** [review]
lgtm, awesome.. thank you @JanKoehnlein !

**Comment by JanKoehnlein** [comment]
Excellent, thanks for merging!

In order to get the repo pre-built automatically on each commit, you have to enable the (Gitpod GitHub)[https://www.gitpod.io/docs/prebuilds#configure-the-github-app] app.

**Pull request merged**
