### PR TITLE
fixed all opt.semgrep.err-nil-check issues

### PR DESCRIPTION
**Pull request by sreeharimohan**
Signed-off-by: Sreehari Mohan <sreeharimohan11@gmail.com>

All superfluous err nil checks in the pkg folder have been changed.

This does not affect any of the functionalities. It just cleans up unneeded code and reduces the complexity of the functions involved.

### CODE REVIEW

**Comment by mittachaitu** [comment]
@sreeharimohan Can we rebase the PR with master branch to resolve the conflicts?

**Comment by sreeharimohan** [comment]
@mittachaitu Please check now

**Comment by sreeharimohan** [comment]
@mittachaitu Can you please review this PR. This has been pending since some time now.

**Review by mittachaitu — APPROVED** [review]
LGTM

**Pull request merged**
