### PR TITLE
Remove usage of fmt.string in cmd/volume-manager/app/commands.go

### PR DESCRIPTION
**Pull request by soniasingla**

### CODE REVIEW

**Review by mittachaitu — APPROVED** [review]
lgtm

**Comment by soniasingla** [comment]
@kmova can we merge this? thanks

**Comment by soniasingla** [comment]
@kmova ping ;) thanks

**Review by mittachaitu — COMMENTED** [review]
Provided one small comment

**Review by sonasingh46 — APPROVED** [review]

**Pull request merged**
