### PR TITLE
code changes in a better format

### PR DESCRIPTION
**Pull request by nisarg1499**
Signed-off-by: Nisarg Shah nisshah1499@gmail.com

### Changes
Changed code into proper format and better readability.

### CODE REVIEW

**Review by mittachaitu — APPROVED** [review]
lgtm

**Comment by nisarg1499** [comment]
Should we merge this? @mittachaitu

**Review by prateekpandey14 — CHANGES_REQUESTED** [review]
@nisarg1499 can you rebase the PR with master , there are some conflicts

**Comment by nisarg1499** [comment]
> @nisarg1499 can you rebase the PR with master , there are some conflicts

@prateekpandey14 Merge conflicts resolved.

**Comment by nisarg1499** [comment]
@mittachaitu @prateekpandey14 
Should we merge this?

**Comment by nisarg1499** [comment]
@mittachaitu @prateekpandey14 
Should we merge this?

**Review by prateekpandey14 — APPROVED** [review]

**Pull request merged**
